Added feature to shutdown the logger properly if the server crashes unexpectedly
ihmcrobotics/ihmc-robot-data-logger pull request #16
Opened 2024-09-16 15:23 UTC by PotatoPeeler3000

We need to get a certain amount of ticks in a row without a new timestamp, then we shutdown.
This is because if power is lost to the server the JVM doesn't shutdown properly, therefore we can keep logging useless data, this prevents that.

2024-09-17 14:48 UTC, ds58 requested changes

2024-09-17 14:48 UTC, ds58 commented on src/main/java/us/ihmc/robotDataLogger/logger/YoVariableLoggerListener.java
> +         if (ticksWithoutNewTimestamp == TICKS_WITHOUT_DATA_BEFORE_SHUTDOWN)
can you make this `if (!alreadyShutDown && ticksWithoutNewTimestamp >= TICKS_WITHOUT_DATA_BEFORE_SHUTDOWN)`

2024-09-17 14:48 UTC, ds58 commented on src/main/java/us/ihmc/robotDataLogger/logger/YoVariableLoggerListener.java
> +         LogTools.info("This may have already shutdown properly due to the server losing power for an extended amount of time");
Not necessarily because of loss of power. I think you should just make this say `This may have already shutdown properly because the connection to the YoVariableServer was lost`

2024-09-17 23:12 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/YoVariableLoggerListener.java
> +         LogTools.info("This may have already shutdown properly due to the server losing power for an extended amount of time");
Fair, went with: "This may have already shutdown because the connection to the server was lost"

2024-09-17 23:12 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/YoVariableLoggerListener.java
> +         if (ticksWithoutNewTimestamp == TICKS_WITHOUT_DATA_BEFORE_SHUTDOWN)
Ya good call

2024-09-18 14:35 UTC, ds58 approved these changes

2024-09-18 17:07 UTC, merged