Update readme to use Magewell and not use blackmagic
ihmcrobotics/ihmc-robot-data-logger pull request #17
Opened 2024-09-17 14:10 UTC by PotatoPeeler3000

2024-09-17 14:35 UTC, ds58 requested changes

2024-09-17 14:35 UTC, ds58 commented on README.md
> +    - This is deprecated because it only works on Ubuntu 20.04 and is no longer supported by the maintainers of this repository
Can you clarify that "it" refers to https://github.com/ihmcrobotics/ihmc-java-decklink-capture and not the actual hardware. Correct me if I am wrong

2024-09-17 14:35 UTC, ds58 commented on README.md
> +- Install Ubuntu Desktop 22.04 LTS (its convenient to have a GUI to work with)
"its" -> "it's"

2024-09-17 14:35 UTC, ds58 commented on README.md
> +Create a new file ~/.ihmc/CameraSettings.yaml. A basic setup looks like this:
Put ~/.ihmc/CameraSettings.yaml in backticks

2024-09-17 22:40 UTC, PotatoPeeler3000 commented on README.md
> +    - This is deprecated because it only works on Ubuntu 20.04 and is no longer supported by the maintainers of this repository
Ooooo good call!

2024-09-17 22:41 UTC, PotatoPeeler3000 commented on README.md
> +- Install Ubuntu Desktop 22.04 LTS (its convenient to have a GUI to work with)
Yep

2024-09-17 22:41 UTC, PotatoPeeler3000 commented on README.md
> +Create a new file ~/.ihmc/CameraSettings.yaml. A basic setup looks like this:
Yes sir!

2024-09-18 14:35 UTC, ds58 approved these changes

2024-09-18 17:06 UTC, merged