Change how we send models to the Logger
ihmcrobotics/ihmc-robot-data-logger pull request #2
Opened 2024-02-28 21:23 UTC by PotatoPeeler3000

- Change how the models are being sent
- write a couple tests as proof of concept
- changed some print statements to make things more clear
Also learning how to use GitHub with this PR...

2024-02-28 21:27 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/multicastLogDataProtocol/modelLoaders/DefaultLogModelProvider.java
> +   private final String[] topLevelResourceDirectories;
This more accurately follows the naming convention where its used

2024-02-28 21:27 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/YoVariableClientImplementation.java
> +         LogTools.info("Received model, resource bundle, and the works");
Updated the print statements, changed some to comments

2024-02-28 21:27 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/YoVariableLoggerDispatcher.java
> +               LogTools.warn("Not logging the above session");
More clear print

2024-02-28 21:27 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/YoVariableLoggerListener.java
> +      LogTools.info("Log is saved as: ({})" + finalDirectory);
Print the directory where the log is saved so its easier to sanity check the results

2024-02-28 21:27 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/tools/ResourceLoaderTools.java
> +package us.ihmc.tools;
Class to handle the resource loading, now inside the Logger, used to live in IHMC Commons, also cleaned up

2024-02-28 21:27 UTC, PotatoPeeler3000 commented on src/test/java/us/ihmc/tools/compression/ResourceLoaderToolsTest.java
> +package us.ihmc.tools.compression;
Some simple tests to make sure this works, better then nothing

2024-02-28 23:01 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/multicastLogDataProtocol/modelLoaders/DefaultLogModelProvider.java
> +         Pattern zipInclude = Pattern.compile("models\\\\nadia_V17_description\\\\.*");
@SylvainBertrand This is where we can add model directories we want to be included, currently we only send Nadia V17, are there others we want to send?

2024-02-28 23:09 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/tools/ResourceLoaderTools.java
> +package us.ihmc.tools;
The IHMC Commons class was only used for the logger so I moved it here, and added a couple tests which may need more work later

2024-02-28 23:09 UTC, PotatoPeeler3000 commented
Tested on hardware, nothing blew up, looks good

2024-02-28 23:42 UTC, SylvainBertrand requested changes
Main thing is that we shouldn't have nadia specific stuff here. I think we simply need to make the code a little more flexible.

2024-02-28 23:42 UTC, SylvainBertrand commented on src/main/java/us/ihmc/multicastLogDataProtocol/modelLoaders/DefaultLogModelProvider.java
> +         Pattern zipInclude = Pattern.compile("models\\\\nadia_V17_description\\\\.*");
That's not good, this project cannot be Nadia specific.
What we could do, is allow to pass a filter at creation of this class (like a `java.util.fuction.Predicate<String>`) that could be passed down to the `ResourceLoaderTools.createZipBundle(...)`
I think a `Predicate` is better than using a `Pattern`, as it can implement a test using a `Pattern` or something else, so more flexible.

2024-02-28 23:42 UTC, SylvainBertrand commented on src/main/java/us/ihmc/tools/ResourceLoaderTools.java
> +   public static void createZipBundle(OutputStream os, final Pattern include, String... topLevelDirectories) throws IOException
I propose to switch to using a `Predicate<String>` instead of a `Pattern` to filter stuff

2024-02-29 20:45 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/multicastLogDataProtocol/modelLoaders/DefaultLogModelProvider.java
> +      this.filter = filter;
Now we pass in a filter, if we don't want to apply the filter, we set this to null

2024-02-29 20:45 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/multicastLogDataProtocol/modelLoaders/DefaultLogModelProvider.java
> +         ResourceLoaderTools.createZipBundle(os, filter, topLevelResourceDirectories);
Pass down the filter here

2024-02-29 20:45 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/tools/ResourceLoaderTools.java
> +            if (filter == null || filter.test(resourcePath))
If the filter is null, we don't want any filter, so we grab everything, otherwise only grab what the filter matches

2024-02-29 21:01 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/tools/ResourceLoaderTools.java
> +   public static void createZipBundle(OutputStream os, final Pattern include, String... topLevelDirectories) throws IOException
Ya I like that

2024-02-29 21:01 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/multicastLogDataProtocol/modelLoaders/DefaultLogModelProvider.java
> +         Pattern zipInclude = Pattern.compile("models\\\\nadia_V17_description\\\\.*");
True, we can pass down the required models from the robot specific implementation we are looking for

2024-02-29 21:26 UTC, PotatoPeeler3000 commented on src/test/java/us/ihmc/tools/compression/ResourceLoaderToolsTest.java
> +package us.ihmc.tools.compression;
@PotatoPeeler3000 Make a ticket for Jira next iteration to go through and improve these tests, not sure they provide any real value at the moment

2024-02-29 21:27 UTC, PotatoPeeler3000 commented
I'd also like to squash these commits before its merged, several of these commits are useless. @SylvainBertrand I know you are trying that with SCS2, you cool if I do that here?

2024-02-29 22:26 UTC, SylvainBertrand approved these changes
Ok this looks much better!
![pirate-pirate-ship](https://github.com/ihmcrobotics/ihmc-robot-data-logger/assets/15932806/446419b5-1737-4338-8f81-3566bfe0e7ce)

2024-03-01 15:06 UTC, closed without merging

2024-03-01 15:06 UTC, PotatoPeeler3000 commented
Closing pull request with comment, checking out how this feature works...

2024-03-01 15:08 UTC, PotatoPeeler3000 commented
I guess you don't want to close the PR. You want to merge it, oops

2024-03-01 15:11 UTC, PotatoPeeler3000 commented
I think because I force pushed, it wouldn't let me merge this PR, interesting, need to play with that next time. The new PR with the squashed commits is here: https://github.com/ihmcrobotics/ihmc-robot-data-logger/pull/4