Added method to pack the models as a byte array to be sent over the network and received on the client side
ihmcrobotics/ihmc-robot-data-logger pull request #6
Opened 2024-03-25 21:27 UTC by PotatoPeeler3000

2024-03-25 21:52 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/multicastLogDataProtocol/modelLoaders/DefaultLogModelProvider.java
> +    * Returns the byte array of the combined InputStreams to be sent over the network
Even if we have one model, this still works, meta data will be added so on the receiving side that needs to be accounted for

2024-03-25 21:52 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/multicastLogDataProtocol/modelLoaders/DefaultLogModelProvider.java
> +         this.model = packModels(modelsAsStreams);
I like this way of doing things, where we add the meta data regardless. The other option is to check the size of the `modelsAsStream` and if its not greater then 1, send that over with `IOUtils.toByteArray(modelsAsStream)` without any meta data.

2024-03-25 21:52 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/multicastLogDataProtocol/modelLoaders/DefaultLogModelProvider.java
> +         this.model = packModels(modelsAsStreams);
Only thing with this is if clients are not accounting for this on the receiving side, an acompanying PR for SCS2 implements the receiving side to account for the new meta data.

2024-03-26 01:59 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/multicastLogDataProtocol/modelLoaders/DefaultLogModelProvider.java
> +    * Returns the byte array of the combined InputStreams to be sent over the network
The receiving side is in the SCS2 so this PR handles that: https://github.com/ihmcrobotics/simulation-construction-set-2/pull/172

2024-03-26 14:55 UTC, PotatoPeeler3000 commented
The only thing with this is the model.sdf file in a log will have some incorrect tags. Since its being composed, it will have one complete URDF and the next one will be appended below it, so however many files your URDF is it, you will have 
<robot>...
<junkkkkkkk>
</robot>
<robot>
<second URDF>
</robot>
<robot>
<third URDF>
</robot>

Which means it can't be loaded into SCS2 without manual formatting, however all the data is there and its pretty easy  to remove those tags manually.

2024-03-26 14:58 UTC, PotatoPeeler3000 commented
> The only thing with this is the model.sdf file in a log will have some incorrect tags. Since its being composed, it will have one complete URDF and the next one will be appended below it, so however many files your URDF is it, you will have `<robot>... <junkkkkkkk> </robot> <robot> <second URDF> </robot> <robot> <third URDF> </robot>`
> 
> Which means it can't be loaded into SCS2 without manual formatting, however all the data is there and its pretty easy to remove those tags manually.

Also I'm not sure we even use that file, all the models for the URDF are in the log anyways

2024-03-27 14:25 UTC, PotatoPeeler3000 commented
I did look into sending multiple models that get stored in a directory, but that would require a lot of code changes so I thought it was better to add all the models to the byte[] with metadata so it could be split back up.

2024-04-01 20:15 UTC, SylvainBertrand requested changes

2024-04-01 20:15 UTC, SylvainBertrand commented on src/main/java/us/ihmc/multicastLogDataProtocol/modelLoaders/DefaultLogModelProvider.java
> +
Instead of doing this let's combine the models into a single one and ship that. You can use `URDFTools,saveURDFModel()` to write a URDFModel into a output stream

2024-04-02 02:31 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/multicastLogDataProtocol/modelLoaders/DefaultLogModelProvider.java
> +
Yep, that's awesome. Now nothing inside DefaultLogModelViewer has to change so we don't need this PR 🤯 😲

2024-04-02 02:31 UTC, closed without merging