Feature/capture magewell
ihmcrobotics/ihmc-robot-data-logger pull request #8
Opened 2024-07-30 17:26 UTC by PotatoPeeler3000

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/idl/CameraSettings.idl
> +			    MAGEWELL_CAPTURE,
This allows us to check which capture method we want to use

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/idl/LogProperties.idl
> +		string type;    // Type of capture method used
We put the capture type in the robotData.log file so that when you load the log you know how to load it correctly

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/idl/LogProperties.idl
> +		string type;    // Type of capture method used
![image](https://github.com/user-attachments/assets/cc6b8b2b-3f88-435a-a305-310a65d5783d)

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/idl/LogProperties.idl
> +		string type;    // Type of capture method used
And because I changed something in this file I bumped the version to 4.0

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/YoVariableClientImplementation.java
> +    * the controller.
This comment was wrong

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/GStreamerVideoDataLogger.java
This class is experimental

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/LogPropertiesWriter.java
> +   private final static String version = "4.0";
bumped version to deal with saving the capture type

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/MagewellVideoDataLogger.java
This class captures with the logger with the Magewell capture device with HDMI and plugged into the computer with USB, installing software was easy

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/MagewellVideoDataLogger.java
> +            recorder.setVideoCodec(avcodec.AV_CODEC_ID_MJPEG);
This needs to be set correctly

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/MagewellVideoDataLogger.java
> +   public void timestampChanged(long latestTimeStampFromController)
Before this was confusing, we always store the latest timestamp from the controller, and when we get a frame we use that one to save with the frame timestamp. This ensures correctly loading of the log later

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/MagewellVideoDataLogger.java
> +            LogTools.info("----- Saving the current frame at the current controller timestamp -----");
Helpful prints

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/VideoDataLoggerInterface.java
> +      newCamera.setType(captureType);
This had to be passed in to save the capture type to the file

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/YoVariableLoggerListener.java
> +   public YoVariableLoggerListener(File tempDirectory, File finalDirectory, String timestamp, Announcement request)
Formatting

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/YoVariableLoggerListener.java
> +         LogTools.error("Never started logging, cleaning up from host: ", request.getHostNameAsString());
These prints weren't helpful, better now

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/YoVariableLoggerListener.java
> +                     case MAGEWELL_CAPTURE:
If the CameraSettings.yaml file is asking for this capture method, we perform this

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/YoVariableLoggerListener.java
> +                     case MAGEWELL_CAPTURE:
This doesn't break the old versions who may still want to use Blackmagic

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/test/java/us/ihmc/robotDataLogger/captureVideo/ExampleBytedecoWindowsPlayer.java
Haven't tested that in a while but it may work

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/test/java/us/ihmc/robotDataLogger/captureVideo/ExampleBytedecoWindowsScreenRecord.java
This is a good example but not sure if it works

2024-07-30 23:21 UTC, PotatoPeeler3000 commented on src/test/java/us/ihmc/robotDataLogger/captureVideo/ExampleMagewellCapture.java
This does work, and is good as well

2024-08-05 21:59 UTC, ds58 requested changes

2024-08-05 21:59 UTC, ds58 commented on build.gradle.kts
> +   api("org.bytedeco:javacv-platform:1.5.10")
Can you change this to only include the platforms that the logger supports? I.e. windows-x86_64, linux-x86_64

2024-08-05 21:59 UTC, ds58 commented on src/main/java/us/ihmc/robotDataLogger/logger/YoVariableLoggerListener.java
> +                     case MAGEWELL_CAPTURE:
maybe stick to the naming convention? I.e. CAPTURE_CARD_MAGEWELL

2024-08-05 21:59 UTC, ds58 commented on src/test/java/us/ihmc/robotDataLogger/captureVideo/ExampleBytedecoWindowsScreenRecord.java
> +public class ExampleBytedecoWindowsScreenRecord
Can this be called ExampleJavaCVWindowsScreenRecord or ExampleFFmpegWindowsScreenRecord?

2024-08-07 21:42 UTC, ds58 commented
Can you add me back as a review when it's ready?

2024-08-08 19:21 UTC, PotatoPeeler3000 commented on src/test/java/us/ihmc/robotDataLogger/captureVideo/ExampleBytedecoWindowsScreenRecord.java
> +public class ExampleBytedecoWindowsScreenRecord
I think the Bytedeco is important cause thats the jar that gets pulled in, the FFMPEGFrameRecorder is a part of the Bytedeco library

2024-08-08 19:27 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/YoVariableLoggerListener.java
> +                     case MAGEWELL_CAPTURE:
Ya need to think about that, we can't change the CAPTURE_CARD one cause that lives in the CameraSettings.yaml file. There are only two options so I'm not too worried about a convention

2024-08-08 19:41 UTC, rjgriffin42 commented on src/main/java/us/ihmc/robotDataLogger/YoVariableClientImplementation.java
> +    * the controller.
Technically it's whenever it's arrived from the YoVariableServer, right? It doesn't have to be a controller. (e..g. the kinematics streaming logs)

2024-08-08 19:42 UTC, ds58 commented on src/test/java/us/ihmc/robotDataLogger/captureVideo/ExampleBytedecoWindowsScreenRecord.java
> +public class ExampleBytedecoWindowsScreenRecord
Bytedeco is not a library. JavaCV is a library, javacpp is a library, and javacpp-ffmpeg is a library

2024-08-08 19:45 UTC, rjgriffin42 commented on src/test/java/us/ihmc/robotDataLogger/captureVideo/ExampleBytedecoWindowsScreenRecord.java
> +            recorder.setFrameRate(60);
is it important that the grabber and recorder use the same frame rate? If it is, should you make a variable called framerate and pass that in, to future proof against some dummy trying to change the rate?

2024-08-08 19:47 UTC, rjgriffin42 commented on src/main/java/us/ihmc/robotDataLogger/logger/MagewellVideoDataLogger.java
> +         long videoTimestamp = 1000 * (System.currentTimeMillis() - startTime);
I'd advocate pulling this into a tools class with a test to convert from millis to seconds.

2024-08-08 19:48 UTC, rjgriffin42 commented on src/main/java/us/ihmc/robotDataLogger/logger/MagewellVideoDataLogger.java
> +         if (timeStampFromControllerCounter == 5000)
what is the 5000 an indicator for? The warning could be more clear, and the 5000 is a magic secret number.

2024-08-08 19:49 UTC, rjgriffin42 commented on src/main/java/us/ihmc/robotDataLogger/logger/MagewellVideoDataLogger.java
> +            System.out.println("Whew we did it! Done");
Should this be LogTools

2024-08-08 19:50 UTC, rjgriffin42 commented on src/test/java/us/ihmc/robotDataLogger/captureVideo/ExampleBytedecoWindowsScreenRecord.java
> +               long videoTS = 1000 * (System.currentTimeMillis() - startTime);
see comment on unit conversions from earlier.

2024-08-08 19:53 UTC, ds58 commented on src/main/java/us/ihmc/robotDataLogger/logger/MagewellVideoDataLogger.java
> +      int captureWidth = 1280;
Can the resolution be configurable? What if we want to capture at 1080p or 4k?

2024-08-08 19:53 UTC, ds58 commented on src/main/java/us/ihmc/robotDataLogger/logger/YoVariableLoggerListener.java
> +                     case MAGEWELL_CAPTURE:
Yeah I was saying match the one we can't change. So we have: CAPTURE_CARD and CAPTURE_CARD_MAGEWELL

2024-08-21 18:29 UTC, PotatoPeeler3000 commented on src/main/java/us/ihmc/robotDataLogger/logger/MagewellVideoDataLogger.java
> +      int captureWidth = 1280;
It can be configurable, but I don't think we can capture 4k unless the device is able to process it, so this will require more testing in the future

2024-08-21 18:29 UTC, merged